#!/usr/bin/env sh

spacebar -m config position             top
spacebar -m config height               26
spacebar -m config power_icon_color     0xffcd950c
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xffa8a8a8
spacebar -m config clock_icon_color     0xffa8a8a8
spacebar -m config power_icon_strip     "  "
spacebar -m config space_icon           ""
spacebar -m config clock_icon           " "
spacebar -m config dnd_icon             
spacebar -m config text_font            "Iosevka term:Bold:12.0"
spacebar -m config icon_font            "Iosevka term:Bold:12.0"
spacebar -m config background_color     0x60202020
spacebar -m config foreground_color     0xffe2e2e2
spacebar -m config space_icon_color     0xff00aaff # selected
# spacebar -m config space_icon_strip     1 2 3 4 5 6 7 8 9
spacebar -m config space_icon_strip     1.Web 2.Dev 3.Tools Q.Whatsapp W.Slack E.Mail A.Calendar EOL
spacebar -m config clock_format         "%d/%m %R"